version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --upgrade --force-reinstall . "awscli>1.20.30"

  build:
    commands:
      - set -e
      - export PYTHONUNBUFFERED=TRUE
      - export DATE=$(date +"%Y%m%d%H%M")
      - export SESSION_NAME="CrossAccountBuild-${DATE}"
      - echo "$SESSION_NAME"
      - export SAGEMAKER_PROJECT_NAME_ID="${SAGEMAKER_PROJECT_NAME}-${SAGEMAKER_PROJECT_ID}"

      - |
        export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" \
            $(aws sts assume-role \
            --role-arn arn:aws:iam::${ACCOUNT_ID}:role/CrossAccountCodeBuildStep-${SAGEMAKER_PROJECT_NAME_ID} \
            --role-session-name ${SESSION_NAME} \
            --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" \
            --output text))

      - echo "Assumed role in ${ACCOUNT_ID}"
      - export SAGEMAKER_PIPELINE_ROLE_ARN=$(aws ssm get-parameter --name "/mlops/tooling_impl/sagemaker_role_arn" --query "Parameter.Value" --output text)
      - echo "Sagemaker role ${SAGEMAKER_PIPELINE_ROLE_ARN}"

      - |
        run-pipeline --module-name ml_pipelines.training.pipeline \
          --role-arn $SAGEMAKER_PIPELINE_ROLE_ARN \
          --tags "[{\"Key\":\"sagemaker:project-name\", \"Value\":\"${SAGEMAKER_PROJECT_NAME}\"}, {\"Key\":\"sagemaker:project-id\", \"Value\":\"${SAGEMAKER_PROJECT_ID}\"}]" \
          --kwargs "{\"region\":\"${AWS_REGION}\",\"role\":\"${SAGEMAKER_PIPELINE_ROLE_ARN}\",\"default_bucket\":\"${ARTIFACT_BUCKET}\",\"pipeline_name\":\"${SAGEMAKER_PROJECT_NAME_ID}\",\"model_package_group_name\":\"${MODEL_PACKAGE_GROUP_NAME}\",\"base_job_prefix\":\"${SAGEMAKER_PROJECT_NAME_ID}\", \"bucket_kms_id\":\"${ARTIFACT_BUCKET_KMS_ID}\"}"
      
      - echo "Create/Update of the SageMaker Pipeline and execution completed."
